import { siteConfig } from '@/config/site';

export default function Verdict({ verdict }: { verdict: string }) {
  return (
    <>
      <section className="border-2 border-accent bg-accent-light rounded-xl p-8 mb-8">
        <h2 className="text-sm font-bold text-accent mb-3 uppercase tracking-wide">The Verdict</h2>
        <p className="text-foreground text-lg leading-relaxed font-medium">{verdict}</p>
      </section>

      <div className="bg-card-bg rounded-xl p-6 mb-10 text-xs text-muted leading-relaxed">
        <p className="font-bold text-foreground mb-2 text-sm">Disclaimer</p>
        <p>
          This analysis is AI-generated by {siteConfig.name} for educational and entertainment
          purposes only. It is not financial advice. {siteConfig.name} is not affiliated with
          The Motley Fool, Seeking Alpha, Zacks, or any financial institution. Always do your
          own research and consult a qualified financial advisor before making investment decisions.
        </p>
      </div>
    </>
  );
}
