import { NextRequest, NextResponse } from 'next/server';
import { verifySession } from '@/lib/auth';
import { getArticleBySlug } from '@/lib/content';
import { generateSocialCopy } from '@/lib/social-copy';
import nodemailer from 'nodemailer';

export async function POST(req: NextRequest) {
  if (!verifySession(req)) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const { slug, article: clientArticle } = await req.json();
  if (!slug) {
    return NextResponse.json({ error: 'Missing slug' }, { status: 400 });
  }

  // Prefer article passed from client (works on Vercel's read-only FS)
  const article = clientArticle || getArticleBySlug(slug);
  if (!article) {
    return NextResponse.json({ error: 'Article not found' }, { status: 404 });
  }

  // Generate social copy via Haiku
  const copy = await generateSocialCopy(article);

  // Send email if credentials are configured
  let emailSent = false;
  const emailTo = process.env.DISTRIBUTE_EMAIL;
  const emailPass = process.env.GMAIL_APP_PASSWORD;

  if (emailTo && emailPass) {
    try {
      const transporter = nodemailer.createTransport({
        service: 'gmail',
        auth: {
          user: emailTo,
          pass: emailPass,
        },
      });

      const htmlBody = `
<h2>${article.title}</h2>
<p><a href="${copy.articleUrl}">${copy.articleUrl}</a></p>

<hr>
<h3>Reddit</h3>
<p><strong>Subreddits:</strong> ${copy.reddit.subreddits.map(s => `r/${s}`).join(', ')}</p>
<p><strong>Title:</strong> ${copy.reddit.title}</p>
<div style="background:#f5f5f5;padding:12px;border-radius:8px;white-space:pre-wrap;font-family:sans-serif;font-size:14px;">${copy.reddit.body}</div>

<hr>
<h3>X (Twitter)</h3>
<div style="background:#f5f5f5;padding:12px;border-radius:8px;font-family:sans-serif;font-size:14px;">${copy.twitter}</div>
<p style="color:#888;font-size:12px;">${copy.twitter.length}/280 chars</p>

<hr>
<h3>Instagram</h3>
<div style="background:#f5f5f5;padding:12px;border-radius:8px;white-space:pre-wrap;font-family:sans-serif;font-size:14px;">${copy.instagram}</div>

<hr>
<p style="color:#888;font-size:11px;">Generated by BullOrBS distribute pipeline</p>
`;

      await transporter.sendMail({
        from: `BullOrBS <${emailTo}>`,
        to: emailTo,
        subject: `Distribute: ${article.title}`,
        html: htmlBody,
      });

      emailSent = true;
    } catch (err) {
      console.log('[Distribute] Email failed:', err instanceof Error ? err.message : err);
    }
  }

  return NextResponse.json({
    success: true,
    copy,
    emailSent,
    emailConfigured: !!(emailTo && emailPass),
  });
}
