import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Disclaimer & Terms',
  description:
    'Legal disclaimer for NotSoFoolAI. All content is AI-generated for educational purposes. Not financial advice.',
};

export default function DisclaimerPage() {
  return (
    <div className="mx-auto max-w-3xl px-6 py-16">
      <h1 className="text-3xl font-bold mb-8">Disclaimer &amp; Terms</h1>

      <div className="space-y-8 text-muted leading-relaxed text-sm">
        <section>
          <h2 className="text-lg font-bold text-foreground mb-3">Not Financial Advice</h2>
          <p>
            All content on NotSoFoolAI is generated by artificial intelligence
            for educational and entertainment purposes only. Nothing on this
            website constitutes financial advice, investment advice, trading
            advice, or any other form of professional advice.
          </p>
          <p className="mt-3">
            You should not make any financial decisions based solely on the
            content provided on this website. Always consult with a qualified
            financial advisor and conduct your own research before making
            investment decisions.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-foreground mb-3">AI-Generated Content</h2>
          <p>
            All analysis, opinions, and recommendations on this website are
            generated by AI language models. AI can make errors, hallucinate
            facts, misinterpret data, and produce incorrect conclusions. We
            publish the full reasoning chain specifically so you can evaluate
            the analysis yourself.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-foreground mb-3">No Affiliation</h2>
          <p>
            NotSoFoolAI is not affiliated with, endorsed by, sponsored by, or
            in any way connected to The Motley Fool, Motley Fool Canada, or
            any of their subsidiaries, partners, or affiliates. The Motley
            Fool is a registered trademark of The Motley Fool, LLC.
          </p>
          <p className="mt-3">
            Our commentary on publicly available stock recommendations is
            protected under fair dealing (Canada) and fair use (United States)
            provisions as criticism, commentary, and education. We reference
            only publicly available information.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-foreground mb-3">No Guarantees</h2>
          <p>
            Past performance does not guarantee future results. Stock prices
            can go down as well as up. You may lose some or all of your
            invested capital. NotSoFoolAI makes no guarantees about the
            accuracy, completeness, or timeliness of any content.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-foreground mb-3">Commentary &amp; Satire</h2>
          <p>
            Some content on this website is satirical or comedic in nature.
            Our &quot;Roast&quot; series provides critical commentary on publicly
            available stock recommendations. This commentary is protected
            speech under both the Canadian Charter of Rights and Freedoms
            and the First Amendment of the United States Constitution.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-foreground mb-3">Data Accuracy</h2>
          <p>
            Stock prices, financial ratios, analyst targets, and other data
            referenced in our analysis are sourced from publicly available
            information via web search at the time of generation. This data
            may be delayed, incomplete, or inaccurate. Always verify data
            through official sources before making decisions.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-foreground mb-3">Privacy</h2>
          <p>
            If you subscribe to our newsletter, we collect your email address
            solely for the purpose of sending you our newsletter. We do not
            sell, share, or distribute your email address to third parties.
            You may unsubscribe at any time.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-foreground mb-3">Contact</h2>
          <p>
            For questions, concerns, or takedown requests, please contact us
            at <span className="text-accent">hello@notsofoolai.com</span>.
          </p>
        </section>

        <p className="text-xs text-muted pt-4 border-t border-card-border">
          Last updated: {new Date().toISOString().split('T')[0]}
        </p>
      </div>
    </div>
  );
}
